Repository SamGCM/lets-battleship, pull requests merged in 2022-01, with the labels that each got.

#5 Added new methods in class player, and main.
  battleship/src/com/battleship/Main.java
  battleship/src/com/battleship/Player.java
  out/production/lets-battleship/com/battleship/Main.class
  out/production/lets-battleship/com/battleship/Player.class
Labels: enhancement

#6 Added players score on board and fixed coordinate input.
  .idea/runConfigurations.xml
  battleship/src/com/battleship/Board.java
  battleship/src/com/battleship/Computer.java
  battleship/src/com/battleship/Main.java
  battleship/src/com/battleship/Player.java
  out/production/lets-battleship/com/battleship/Board.class
  out/production/lets-battleship/com/battleship/Computer.class
  out/production/lets-battleship/com/battleship/Main.class
  out/production/lets-battleship/com/battleship/Player.class
Labels: bug, enhancement

#8 fixed the feature when the player or the computer wins the match
  battleship/src/com/battleship/Main.java
  out/production/lets-battleship/com/battleship/Main.class
Labels: bug
